version: "3"
services:
  helsinki:
    environment:
      - CITY=helsinki
      - PORT=5000
      - OTHER_HOSTS=turku:5000,oulu:5000
    build: .
    ports:
      - "5001:5000"
    volumes:
      - .:/code
  turku:
    environment:
      - CITY=turku
      - PORT=5000
      - OTHER_HOSTS=helsinki:5000,oulu:5000
    build: .
    ports:
      - "5002:5000"
    volumes:
      - .:/code
  oulu:
    environment:
      - CITY=oulu
      - PORT=5000
      - OTHER_HOSTS=helsinki:5000,turku:5000
    build: .
    ports:
      - "5003:5000"
    volumes:
      - .:/code
