# DRAFT
version: "3"
services:
  helsinki:
    environment:
      - CITY=helsinki
    build: .
    ports:
      - "5001:5000"
  moscow:
    environment:
      - CITY=moscow
    build: .
    ports:
      - "5002:5000"
  vaasa:
    environment:
      - CITY=vaasa
    build: .
    ports:
      - "5003:5000"
  dublin:
    environment:
      - CITY=dublin
    build: .
    ports:
      - "5004:5000"
  quito:
    environment:
      - CITY=quito
    build: .
    ports:
      - "5005:5000"
  vancouver:
    environment:
      - CITY=vancouver
    build: .
    ports:
      - "5006:5000"
  lima:
    environment:
      - CITY=lima
    build: .
    ports:
      - "5007:5000"
  shanghai:
    environment:
      - CITY=shanghai
    build: .
    ports:
      - "5008:5000"
  newcastle:
    environment:
      - CITY=newcastle
    build: .
    ports:
      - "5009:5000"
  perth:
    environment:
      - CITY=perth
    build: .
    ports:
      - "5010:5000"
  ouagadougou:
    environment:
      - CITY=ouagadougou
    build: .
    ports:
      - "5011:5000"
  shenzhen:
    environment:
      - CITY=shenzhen
    build: .
    ports:
      - "5012:5000"
  pyongyang:
    environment:
      - CITY=pyongyang
    build: .
    ports:
      - "5013:5000"
  longyearbyen:
    environment:
      - CITY=longyearbyen
    build: .
    ports:
      - "5014:5000"
  capetown:
    environment:
      - CITY=capetown
    build: .
    ports:
      - "5015:5000"
  almaty:
    environment:
      - CITY=almaty
    build: .
    ports:
      - "5016:5000"
